/**
 * Demo Data - Y Combinator themed data for YC demo
 *
 * 50 employees across YC's departments with behavioral signals,
 * recruiting pipeline, PTO data, and engagement metrics.
 */

export interface DemoEmployee {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  job_title: string;
  department: string;
  team?: string;
  manager_id?: string;
  hire_date: string;
  salary: number;
  level: string;
  location: string;
  remote_status: 'remote' | 'hybrid' | 'onsite';
  profile_image_url?: string;
  // Behavioral signals
  engagement_score: number;
  performance_rating: number;
  flight_risk: 'low' | 'medium' | 'high';
  flight_risk_score: number;
  last_promotion?: string;
  pto_balance: number;
  pto_used: number;
  // AI-detected signals
  signals: {
    communication_trend: 'increasing' | 'stable' | 'declining';
    meeting_load: 'light' | 'moderate' | 'heavy';
    focus_time_hours: number;
    sentiment_score: number;
    collaboration_score: number;
  };
}

export interface DemoCandidate {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  current_company?: string;
  current_title?: string;
  applied_position: string;
  stage: 'applied' | 'screening' | 'interview' | 'offer' | 'hired' | 'rejected';
  applied_date: string;
  source: string;
  ai_match_score: number;
  skills: string[];
  experience_years: number;
}

export interface DemoPTORequest {
  id: string;
  employee_id: string;
  type: 'vacation' | 'sick' | 'personal';
  start_date: string;
  end_date: string;
  days: number;
  status: 'pending' | 'approved' | 'denied';
  reason?: string;
}

export interface DemoTeam {
  id: string;
  name: string;
  department: string;
  manager_id: string;
  member_count: number;
  health_score: number;
  avg_engagement: number;
}

// ============================================================================
// EMPLOYEES (50) - Y Combinator
// ============================================================================

export const demoEmployees: DemoEmployee[] = [
  // LEADERSHIP (5)
  {
    id: 'emp_001',
    first_name: 'Garry',
    last_name: 'Tan',
    email: 'garry@ycombinator.com',
    job_title: 'President & CEO',
    department: 'Leadership',
    hire_date: '2022-01-01',
    salary: 450000,
    level: 'C-Level',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 96,
    performance_rating: 4.9,
    flight_risk: 'low',
    flight_risk_score: 5,
    pto_balance: 25,
    pto_used: 8,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 8,
      sentiment_score: 0.92,
      collaboration_score: 98,
    },
  },
  {
    id: 'emp_002',
    first_name: 'Jared',
    last_name: 'Friedman',
    email: 'jared@ycombinator.com',
    job_title: 'Managing Partner',
    department: 'Leadership',
    hire_date: '2018-03-15',
    salary: 420000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 94,
    performance_rating: 4.8,
    flight_risk: 'low',
    flight_risk_score: 8,
    pto_balance: 22,
    pto_used: 10,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 10,
      sentiment_score: 0.89,
      collaboration_score: 95,
    },
  },
  {
    id: 'emp_003',
    first_name: 'Diana',
    last_name: 'Hu',
    email: 'diana@ycombinator.com',
    job_title: 'Managing Partner',
    department: 'Leadership',
    hire_date: '2019-06-01',
    salary: 415000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 93,
    performance_rating: 4.7,
    flight_risk: 'low',
    flight_risk_score: 10,
    pto_balance: 20,
    pto_used: 12,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'heavy',
      focus_time_hours: 9,
      sentiment_score: 0.88,
      collaboration_score: 94,
    },
  },
  {
    id: 'emp_004',
    first_name: 'Dalton',
    last_name: 'Caldwell',
    email: 'dalton@ycombinator.com',
    job_title: 'Managing Partner',
    department: 'Leadership',
    hire_date: '2013-04-01',
    salary: 430000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 91,
    performance_rating: 4.8,
    flight_risk: 'low',
    flight_risk_score: 7,
    last_promotion: '2020-01-01',
    pto_balance: 24,
    pto_used: 9,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 11,
      sentiment_score: 0.86,
      collaboration_score: 93,
    },
  },
  {
    id: 'emp_005',
    first_name: 'Michael',
    last_name: 'Seibel',
    email: 'michael@ycombinator.com',
    job_title: 'Managing Partner',
    department: 'Leadership',
    hire_date: '2014-01-15',
    salary: 425000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 95,
    performance_rating: 4.9,
    flight_risk: 'low',
    flight_risk_score: 6,
    pto_balance: 23,
    pto_used: 7,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 10,
      sentiment_score: 0.91,
      collaboration_score: 96,
    },
  },

  // GROUP PARTNERS (15)
  {
    id: 'emp_006',
    first_name: 'Gustaf',
    last_name: 'Alstromer',
    email: 'gustaf@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Growth',
    manager_id: 'emp_002',
    hire_date: '2017-09-01',
    salary: 380000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 89,
    performance_rating: 4.5,
    flight_risk: 'low',
    flight_risk_score: 15,
    pto_balance: 18,
    pto_used: 14,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 12,
      sentiment_score: 0.84,
      collaboration_score: 90,
    },
  },
  {
    id: 'emp_007',
    first_name: 'Aaron',
    last_name: 'Epstein',
    email: 'aaron@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Enterprise',
    manager_id: 'emp_002',
    hire_date: '2019-01-15',
    salary: 375000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 87,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 18,
    pto_balance: 16,
    pto_used: 11,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 10,
      sentiment_score: 0.82,
      collaboration_score: 88,
    },
  },
  {
    id: 'emp_008',
    first_name: 'Brad',
    last_name: 'Flora',
    email: 'brad@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Consumer',
    manager_id: 'emp_003',
    hire_date: '2020-03-01',
    salary: 370000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 85,
    performance_rating: 4.3,
    flight_risk: 'medium',
    flight_risk_score: 35,
    pto_balance: 14,
    pto_used: 16,
    signals: {
      communication_trend: 'declining',
      meeting_load: 'heavy',
      focus_time_hours: 8,
      sentiment_score: 0.72,
      collaboration_score: 84,
    },
  },
  {
    id: 'emp_009',
    first_name: 'Harj',
    last_name: 'Taggar',
    email: 'harj@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Enterprise',
    manager_id: 'emp_002',
    hire_date: '2018-06-01',
    salary: 385000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 92,
    performance_rating: 4.6,
    flight_risk: 'low',
    flight_risk_score: 12,
    last_promotion: '2022-01-01',
    pto_balance: 19,
    pto_used: 8,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 11,
      sentiment_score: 0.87,
      collaboration_score: 91,
    },
  },
  {
    id: 'emp_010',
    first_name: 'Nicolas',
    last_name: 'Dessaigne',
    email: 'nicolas@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'AI/ML',
    manager_id: 'emp_003',
    hire_date: '2021-01-15',
    salary: 375000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 94,
    performance_rating: 4.7,
    flight_risk: 'low',
    flight_risk_score: 9,
    pto_balance: 20,
    pto_used: 6,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'moderate',
      focus_time_hours: 14,
      sentiment_score: 0.90,
      collaboration_score: 93,
    },
  },
  {
    id: 'emp_011',
    first_name: 'Tom',
    last_name: 'Blomfield',
    email: 'tom@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Fintech',
    manager_id: 'emp_004',
    hire_date: '2021-06-01',
    salary: 380000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 91,
    performance_rating: 4.6,
    flight_risk: 'low',
    flight_risk_score: 14,
    pto_balance: 17,
    pto_used: 10,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 10,
      sentiment_score: 0.86,
      collaboration_score: 90,
    },
  },
  {
    id: 'emp_012',
    first_name: 'Pete',
    last_name: 'Koomen',
    email: 'pete@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Developer Tools',
    manager_id: 'emp_004',
    hire_date: '2019-09-01',
    salary: 375000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 88,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 19,
    pto_balance: 15,
    pto_used: 12,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 13,
      sentiment_score: 0.83,
      collaboration_score: 87,
    },
  },
  {
    id: 'emp_013',
    first_name: 'Surbhi',
    last_name: 'Sarna',
    email: 'surbhi@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Healthcare',
    manager_id: 'emp_003',
    hire_date: '2022-03-01',
    salary: 365000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 93,
    performance_rating: 4.5,
    flight_risk: 'low',
    flight_risk_score: 11,
    pto_balance: 18,
    pto_used: 7,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'moderate',
      focus_time_hours: 15,
      sentiment_score: 0.89,
      collaboration_score: 92,
    },
  },
  {
    id: 'emp_014',
    first_name: 'David',
    last_name: 'Lieb',
    email: 'david.l@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Consumer',
    manager_id: 'emp_005',
    hire_date: '2020-01-15',
    salary: 370000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 86,
    performance_rating: 4.3,
    flight_risk: 'low',
    flight_risk_score: 22,
    pto_balance: 14,
    pto_used: 13,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 9,
      sentiment_score: 0.81,
      collaboration_score: 86,
    },
  },
  {
    id: 'emp_015',
    first_name: 'Kat',
    last_name: 'Manalac',
    email: 'kat@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Outreach',
    manager_id: 'emp_005',
    hire_date: '2015-06-01',
    salary: 390000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 90,
    performance_rating: 4.5,
    flight_risk: 'low',
    flight_risk_score: 16,
    last_promotion: '2021-01-01',
    pto_balance: 16,
    pto_used: 11,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 8,
      sentiment_score: 0.85,
      collaboration_score: 91,
    },
  },
  {
    id: 'emp_016',
    first_name: 'Nan',
    last_name: 'Li',
    email: 'nan@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Enterprise',
    manager_id: 'emp_002',
    hire_date: '2022-09-01',
    salary: 360000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 95,
    performance_rating: 4.6,
    flight_risk: 'low',
    flight_risk_score: 8,
    pto_balance: 20,
    pto_used: 4,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'moderate',
      focus_time_hours: 16,
      sentiment_score: 0.91,
      collaboration_score: 94,
    },
  },
  {
    id: 'emp_017',
    first_name: 'Reshma',
    last_name: 'Khilnani',
    email: 'reshma@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'AI/ML',
    manager_id: 'emp_003',
    hire_date: '2023-01-15',
    salary: 355000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 92,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 13,
    pto_balance: 19,
    pto_used: 5,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'moderate',
      focus_time_hours: 14,
      sentiment_score: 0.88,
      collaboration_score: 91,
    },
  },
  {
    id: 'emp_018',
    first_name: 'Tyler',
    last_name: 'Bosmeny',
    email: 'tyler@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Growth',
    manager_id: 'emp_004',
    hire_date: '2020-06-01',
    salary: 370000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 84,
    performance_rating: 4.2,
    flight_risk: 'medium',
    flight_risk_score: 38,
    pto_balance: 12,
    pto_used: 15,
    signals: {
      communication_trend: 'declining',
      meeting_load: 'heavy',
      focus_time_hours: 7,
      sentiment_score: 0.74,
      collaboration_score: 82,
    },
  },
  {
    id: 'emp_019',
    first_name: 'Calvin',
    last_name: 'French-Owen',
    email: 'calvin@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Developer Tools',
    manager_id: 'emp_004',
    hire_date: '2021-09-01',
    salary: 365000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 89,
    performance_rating: 4.5,
    flight_risk: 'low',
    flight_risk_score: 17,
    pto_balance: 17,
    pto_used: 9,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 12,
      sentiment_score: 0.84,
      collaboration_score: 88,
    },
  },
  {
    id: 'emp_020',
    first_name: 'Eric',
    last_name: 'Migicovsky',
    email: 'eric@ycombinator.com',
    job_title: 'Group Partner',
    department: 'Partners',
    team: 'Hardware',
    manager_id: 'emp_005',
    hire_date: '2018-01-15',
    salary: 380000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 87,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 20,
    pto_balance: 15,
    pto_used: 12,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 13,
      sentiment_score: 0.82,
      collaboration_score: 87,
    },
  },

  // VISITING PARTNERS (5)
  {
    id: 'emp_021',
    first_name: 'Paul',
    last_name: 'Buchheit',
    email: 'paul.b@ycombinator.com',
    job_title: 'Visiting Partner',
    department: 'Partners',
    team: 'Visiting',
    manager_id: 'emp_001',
    hire_date: '2010-01-01',
    salary: 350000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'remote',
    engagement_score: 82,
    performance_rating: 4.6,
    flight_risk: 'low',
    flight_risk_score: 25,
    pto_balance: 20,
    pto_used: 8,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'light',
      focus_time_hours: 20,
      sentiment_score: 0.80,
      collaboration_score: 78,
    },
  },
  {
    id: 'emp_022',
    first_name: 'Kevin',
    last_name: 'Hale',
    email: 'kevin.h@ycombinator.com',
    job_title: 'Visiting Partner',
    department: 'Partners',
    team: 'Visiting',
    manager_id: 'emp_001',
    hire_date: '2016-03-01',
    salary: 345000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'remote',
    engagement_score: 79,
    performance_rating: 4.3,
    flight_risk: 'medium',
    flight_risk_score: 42,
    pto_balance: 18,
    pto_used: 14,
    signals: {
      communication_trend: 'declining',
      meeting_load: 'light',
      focus_time_hours: 18,
      sentiment_score: 0.72,
      collaboration_score: 75,
    },
  },
  {
    id: 'emp_023',
    first_name: 'Adora',
    last_name: 'Cheung',
    email: 'adora@ycombinator.com',
    job_title: 'Visiting Partner',
    department: 'Partners',
    team: 'Visiting',
    manager_id: 'emp_001',
    hire_date: '2017-06-01',
    salary: 340000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 85,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 21,
    pto_balance: 16,
    pto_used: 11,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 14,
      sentiment_score: 0.81,
      collaboration_score: 84,
    },
  },
  {
    id: 'emp_024',
    first_name: 'Qasar',
    last_name: 'Younis',
    email: 'qasar@ycombinator.com',
    job_title: 'Visiting Partner',
    department: 'Partners',
    team: 'Visiting',
    manager_id: 'emp_001',
    hire_date: '2015-09-01',
    salary: 355000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'remote',
    engagement_score: 81,
    performance_rating: 4.2,
    flight_risk: 'medium',
    flight_risk_score: 36,
    pto_balance: 14,
    pto_used: 13,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'light',
      focus_time_hours: 16,
      sentiment_score: 0.76,
      collaboration_score: 79,
    },
  },
  {
    id: 'emp_025',
    first_name: 'Ali',
    last_name: 'Rowghani',
    email: 'ali@ycombinator.com',
    job_title: 'Visiting Partner',
    department: 'Partners',
    team: 'Visiting',
    manager_id: 'emp_001',
    hire_date: '2014-06-01',
    salary: 360000,
    level: 'Partner',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 83,
    performance_rating: 4.3,
    flight_risk: 'low',
    flight_risk_score: 24,
    pto_balance: 15,
    pto_used: 12,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 15,
      sentiment_score: 0.79,
      collaboration_score: 82,
    },
  },

  // OPERATIONS (12)
  {
    id: 'emp_026',
    first_name: 'Lindsay',
    last_name: 'Amos',
    email: 'lindsay@ycombinator.com',
    job_title: 'VP of Operations',
    department: 'Operations',
    hire_date: '2019-04-01',
    salary: 285000,
    level: 'VP',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 92,
    performance_rating: 4.7,
    flight_risk: 'low',
    flight_risk_score: 12,
    last_promotion: '2022-06-01',
    pto_balance: 18,
    pto_used: 9,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 10,
      sentiment_score: 0.87,
      collaboration_score: 93,
    },
  },
  {
    id: 'emp_027',
    first_name: 'Stephanie',
    last_name: 'Chang',
    email: 'stephanie@ycombinator.com',
    job_title: 'Batch Operations Lead',
    department: 'Operations',
    team: 'Batch Ops',
    manager_id: 'emp_026',
    hire_date: '2020-08-01',
    salary: 175000,
    level: 'Lead',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 90,
    performance_rating: 4.5,
    flight_risk: 'low',
    flight_risk_score: 14,
    pto_balance: 16,
    pto_used: 10,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 8,
      sentiment_score: 0.85,
      collaboration_score: 91,
    },
  },
  {
    id: 'emp_028',
    first_name: 'Rachel',
    last_name: 'Hu',
    email: 'rachel@ycombinator.com',
    job_title: 'Batch Operations Manager',
    department: 'Operations',
    team: 'Batch Ops',
    manager_id: 'emp_027',
    hire_date: '2021-06-15',
    salary: 145000,
    level: 'Manager',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 88,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 18,
    pto_balance: 15,
    pto_used: 11,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 12,
      sentiment_score: 0.83,
      collaboration_score: 89,
    },
  },
  {
    id: 'emp_029',
    first_name: 'Marcus',
    last_name: 'Chen',
    email: 'marcus@ycombinator.com',
    job_title: 'Operations Coordinator',
    department: 'Operations',
    team: 'Batch Ops',
    manager_id: 'emp_027',
    hire_date: '2023-01-15',
    salary: 95000,
    level: 'IC2',
    location: 'San Francisco',
    remote_status: 'onsite',
    engagement_score: 91,
    performance_rating: 4.3,
    flight_risk: 'low',
    flight_risk_score: 11,
    pto_balance: 18,
    pto_used: 4,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'moderate',
      focus_time_hours: 14,
      sentiment_score: 0.87,
      collaboration_score: 88,
    },
  },
  {
    id: 'emp_030',
    first_name: 'Emily',
    last_name: 'Kim',
    email: 'emily.k@ycombinator.com',
    job_title: 'Demo Day Lead',
    department: 'Operations',
    team: 'Events',
    manager_id: 'emp_026',
    hire_date: '2020-03-01',
    salary: 165000,
    level: 'Lead',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 68,
    performance_rating: 4.0,
    flight_risk: 'high',
    flight_risk_score: 72,
    pto_balance: 8,
    pto_used: 17,
    signals: {
      communication_trend: 'declining',
      meeting_load: 'heavy',
      focus_time_hours: 4,
      sentiment_score: 0.52,
      collaboration_score: 71,
    },
  },
  {
    id: 'emp_031',
    first_name: 'James',
    last_name: 'Park',
    email: 'james.p@ycombinator.com',
    job_title: 'Events Coordinator',
    department: 'Operations',
    team: 'Events',
    manager_id: 'emp_030',
    hire_date: '2022-09-01',
    salary: 85000,
    level: 'IC2',
    location: 'San Francisco',
    remote_status: 'onsite',
    engagement_score: 74,
    performance_rating: 3.9,
    flight_risk: 'medium',
    flight_risk_score: 45,
    pto_balance: 12,
    pto_used: 13,
    signals: {
      communication_trend: 'declining',
      meeting_load: 'moderate',
      focus_time_hours: 10,
      sentiment_score: 0.68,
      collaboration_score: 76,
    },
  },
  {
    id: 'emp_032',
    first_name: 'Sarah',
    last_name: 'Martinez',
    email: 'sarah.m@ycombinator.com',
    job_title: 'Facilities Manager',
    department: 'Operations',
    team: 'Facilities',
    manager_id: 'emp_026',
    hire_date: '2019-11-01',
    salary: 135000,
    level: 'Manager',
    location: 'San Francisco',
    remote_status: 'onsite',
    engagement_score: 86,
    performance_rating: 4.3,
    flight_risk: 'low',
    flight_risk_score: 19,
    pto_balance: 14,
    pto_used: 12,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 16,
      sentiment_score: 0.81,
      collaboration_score: 85,
    },
  },
  {
    id: 'emp_033',
    first_name: 'Kevin',
    last_name: 'Wong',
    email: 'kevin.w@ycombinator.com',
    job_title: 'Executive Assistant',
    department: 'Operations',
    manager_id: 'emp_001',
    hire_date: '2021-03-01',
    salary: 110000,
    level: 'IC3',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 89,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 15,
    pto_balance: 16,
    pto_used: 9,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 6,
      sentiment_score: 0.84,
      collaboration_score: 90,
    },
  },
  {
    id: 'emp_034',
    first_name: 'Amanda',
    last_name: 'Liu',
    email: 'amanda@ycombinator.com',
    job_title: 'Office Manager',
    department: 'Operations',
    team: 'Facilities',
    manager_id: 'emp_032',
    hire_date: '2022-06-01',
    salary: 95000,
    level: 'IC3',
    location: 'San Francisco',
    remote_status: 'onsite',
    engagement_score: 84,
    performance_rating: 4.2,
    flight_risk: 'low',
    flight_risk_score: 22,
    pto_balance: 15,
    pto_used: 10,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'light',
      focus_time_hours: 20,
      sentiment_score: 0.79,
      collaboration_score: 83,
    },
  },
  {
    id: 'emp_035',
    first_name: 'Jason',
    last_name: 'Thompson',
    email: 'jason.t@ycombinator.com',
    job_title: 'Travel Coordinator',
    department: 'Operations',
    manager_id: 'emp_026',
    hire_date: '2023-04-01',
    salary: 75000,
    level: 'IC2',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 93,
    performance_rating: 4.3,
    flight_risk: 'low',
    flight_risk_score: 10,
    pto_balance: 18,
    pto_used: 3,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'light',
      focus_time_hours: 22,
      sentiment_score: 0.89,
      collaboration_score: 86,
    },
  },
  {
    id: 'emp_036',
    first_name: 'Michelle',
    last_name: 'Rodriguez',
    email: 'michelle.r@ycombinator.com',
    job_title: 'Batch Coordinator',
    department: 'Operations',
    team: 'Batch Ops',
    manager_id: 'emp_027',
    hire_date: '2023-08-01',
    salary: 80000,
    level: 'IC1',
    location: 'San Francisco',
    remote_status: 'onsite',
    engagement_score: 95,
    performance_rating: 4.5,
    flight_risk: 'low',
    flight_risk_score: 7,
    pto_balance: 18,
    pto_used: 2,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'moderate',
      focus_time_hours: 18,
      sentiment_score: 0.92,
      collaboration_score: 91,
    },
  },
  {
    id: 'emp_037',
    first_name: 'David',
    last_name: 'Nguyen',
    email: 'david.n@ycombinator.com',
    job_title: 'Logistics Coordinator',
    department: 'Operations',
    team: 'Events',
    manager_id: 'emp_030',
    hire_date: '2022-11-01',
    salary: 78000,
    level: 'IC2',
    location: 'San Francisco',
    remote_status: 'onsite',
    engagement_score: 81,
    performance_rating: 4.0,
    flight_risk: 'medium',
    flight_risk_score: 40,
    pto_balance: 13,
    pto_used: 12,
    signals: {
      communication_trend: 'declining',
      meeting_load: 'moderate',
      focus_time_hours: 12,
      sentiment_score: 0.71,
      collaboration_score: 78,
    },
  },

  // SOFTWARE/ENGINEERING (8)
  {
    id: 'emp_038',
    first_name: 'David',
    last_name: 'Choi',
    email: 'david.c@ycombinator.com',
    job_title: 'Head of Engineering',
    department: 'Engineering',
    hire_date: '2018-07-01',
    salary: 320000,
    level: 'VP',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 91,
    performance_rating: 4.6,
    flight_risk: 'low',
    flight_risk_score: 14,
    last_promotion: '2021-01-01',
    pto_balance: 17,
    pto_used: 10,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 16,
      sentiment_score: 0.86,
      collaboration_score: 90,
    },
  },
  {
    id: 'emp_039',
    first_name: 'Jennifer',
    last_name: 'Wu',
    email: 'jennifer@ycombinator.com',
    job_title: 'Senior Software Engineer',
    department: 'Engineering',
    team: 'Platform',
    manager_id: 'emp_038',
    hire_date: '2020-09-01',
    salary: 225000,
    level: 'IC5',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 88,
    performance_rating: 4.5,
    flight_risk: 'low',
    flight_risk_score: 17,
    pto_balance: 16,
    pto_used: 11,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'light',
      focus_time_hours: 24,
      sentiment_score: 0.83,
      collaboration_score: 87,
    },
  },
  {
    id: 'emp_040',
    first_name: 'Alex',
    last_name: 'Rivera',
    email: 'alex.r@ycombinator.com',
    job_title: 'Software Engineer',
    department: 'Engineering',
    team: 'Platform',
    manager_id: 'emp_038',
    hire_date: '2022-03-01',
    salary: 185000,
    level: 'IC4',
    location: 'Remote',
    remote_status: 'remote',
    engagement_score: 86,
    performance_rating: 4.3,
    flight_risk: 'low',
    flight_risk_score: 20,
    pto_balance: 15,
    pto_used: 9,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'light',
      focus_time_hours: 28,
      sentiment_score: 0.81,
      collaboration_score: 84,
    },
  },
  {
    id: 'emp_041',
    first_name: 'Chris',
    last_name: 'Lee',
    email: 'chris.l@ycombinator.com',
    job_title: 'Software Engineer',
    department: 'Engineering',
    team: 'Applications',
    manager_id: 'emp_038',
    hire_date: '2023-06-01',
    salary: 165000,
    level: 'IC3',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 92,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 12,
    pto_balance: 18,
    pto_used: 5,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'light',
      focus_time_hours: 26,
      sentiment_score: 0.88,
      collaboration_score: 89,
    },
  },
  {
    id: 'emp_042',
    first_name: 'Michelle',
    last_name: 'Zhang',
    email: 'michelle.z@ycombinator.com',
    job_title: 'Product Designer',
    department: 'Engineering',
    team: 'Design',
    manager_id: 'emp_038',
    hire_date: '2021-11-01',
    salary: 195000,
    level: 'IC4',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 89,
    performance_rating: 4.5,
    flight_risk: 'low',
    flight_risk_score: 16,
    pto_balance: 16,
    pto_used: 10,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 20,
      sentiment_score: 0.84,
      collaboration_score: 88,
    },
  },
  {
    id: 'emp_043',
    first_name: 'Ryan',
    last_name: 'Patel',
    email: 'ryan.p@ycombinator.com',
    job_title: 'Data Engineer',
    department: 'Engineering',
    team: 'Data',
    manager_id: 'emp_038',
    hire_date: '2022-07-01',
    salary: 195000,
    level: 'IC4',
    location: 'Remote',
    remote_status: 'remote',
    engagement_score: 85,
    performance_rating: 4.2,
    flight_risk: 'low',
    flight_risk_score: 23,
    pto_balance: 14,
    pto_used: 12,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'light',
      focus_time_hours: 26,
      sentiment_score: 0.80,
      collaboration_score: 82,
    },
  },
  {
    id: 'emp_044',
    first_name: 'Priya',
    last_name: 'Sharma',
    email: 'priya@ycombinator.com',
    job_title: 'DevOps Engineer',
    department: 'Engineering',
    team: 'Platform',
    manager_id: 'emp_038',
    hire_date: '2021-04-01',
    salary: 205000,
    level: 'IC4',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 87,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 18,
    pto_balance: 15,
    pto_used: 11,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'light',
      focus_time_hours: 24,
      sentiment_score: 0.82,
      collaboration_score: 86,
    },
  },
  {
    id: 'emp_045',
    first_name: 'Nathan',
    last_name: 'Johnson',
    email: 'nathan.j@ycombinator.com',
    job_title: 'Junior Software Engineer',
    department: 'Engineering',
    team: 'Applications',
    manager_id: 'emp_039',
    hire_date: '2024-01-15',
    salary: 145000,
    level: 'IC2',
    location: 'San Francisco',
    remote_status: 'onsite',
    engagement_score: 96,
    performance_rating: 4.3,
    flight_risk: 'low',
    flight_risk_score: 6,
    pto_balance: 18,
    pto_used: 1,
    signals: {
      communication_trend: 'increasing',
      meeting_load: 'light',
      focus_time_hours: 30,
      sentiment_score: 0.93,
      collaboration_score: 90,
    },
  },

  // FINANCE/LEGAL (5)
  {
    id: 'emp_046',
    first_name: 'Robert',
    last_name: 'Chen',
    email: 'robert.c@ycombinator.com',
    job_title: 'CFO',
    department: 'Finance',
    hire_date: '2017-02-01',
    salary: 380000,
    level: 'C-Level',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 88,
    performance_rating: 4.5,
    flight_risk: 'low',
    flight_risk_score: 16,
    pto_balance: 18,
    pto_used: 10,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'heavy',
      focus_time_hours: 12,
      sentiment_score: 0.83,
      collaboration_score: 87,
    },
  },
  {
    id: 'emp_047',
    first_name: 'Lisa',
    last_name: 'Wang',
    email: 'lisa.w@ycombinator.com',
    job_title: 'Senior Controller',
    department: 'Finance',
    manager_id: 'emp_046',
    hire_date: '2019-05-01',
    salary: 195000,
    level: 'IC5',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 84,
    performance_rating: 4.3,
    flight_risk: 'low',
    flight_risk_score: 22,
    pto_balance: 14,
    pto_used: 13,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 18,
      sentiment_score: 0.79,
      collaboration_score: 83,
    },
  },
  {
    id: 'emp_048',
    first_name: 'Michael',
    last_name: 'Foster',
    email: 'michael.f@ycombinator.com',
    job_title: 'General Counsel',
    department: 'Legal',
    hire_date: '2018-09-01',
    salary: 340000,
    level: 'VP',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 86,
    performance_rating: 4.4,
    flight_risk: 'low',
    flight_risk_score: 19,
    pto_balance: 16,
    pto_used: 11,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'moderate',
      focus_time_hours: 14,
      sentiment_score: 0.81,
      collaboration_score: 85,
    },
  },
  {
    id: 'emp_049',
    first_name: 'Jessica',
    last_name: 'Torres',
    email: 'jessica.t@ycombinator.com',
    job_title: 'Corporate Counsel',
    department: 'Legal',
    manager_id: 'emp_048',
    hire_date: '2021-08-01',
    salary: 225000,
    level: 'IC4',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 82,
    performance_rating: 4.2,
    flight_risk: 'medium',
    flight_risk_score: 34,
    pto_balance: 12,
    pto_used: 14,
    signals: {
      communication_trend: 'declining',
      meeting_load: 'moderate',
      focus_time_hours: 16,
      sentiment_score: 0.74,
      collaboration_score: 80,
    },
  },
  {
    id: 'emp_050',
    first_name: 'Andrew',
    last_name: 'Kim',
    email: 'andrew.k@ycombinator.com',
    job_title: 'Accountant',
    department: 'Finance',
    manager_id: 'emp_047',
    hire_date: '2023-02-01',
    salary: 115000,
    level: 'IC3',
    location: 'San Francisco',
    remote_status: 'hybrid',
    engagement_score: 90,
    performance_rating: 4.3,
    flight_risk: 'low',
    flight_risk_score: 13,
    pto_balance: 17,
    pto_used: 6,
    signals: {
      communication_trend: 'stable',
      meeting_load: 'light',
      focus_time_hours: 22,
      sentiment_score: 0.85,
      collaboration_score: 84,
    },
  },
];

// ============================================================================
// CANDIDATES (20) - YC Role Applications
// ============================================================================

export const demoCandidates: DemoCandidate[] = [
  {
    id: 'cand_001',
    first_name: 'Sarah',
    last_name: 'Chen',
    email: 'sarah.chen@stanford.edu',
    current_company: 'Stripe',
    current_title: 'Engineering Manager',
    applied_position: 'Group Partner',
    stage: 'interview',
    applied_date: '2026-01-05',
    source: 'Referral',
    ai_match_score: 94,
    skills: ['Leadership', 'Startup Experience', 'Fundraising', 'Engineering'],
    experience_years: 12,
  },
  {
    id: 'cand_002',
    first_name: 'Marcus',
    last_name: 'Williams',
    email: 'marcus.w@gmail.com',
    current_company: 'Airbnb',
    current_title: 'Director of Product',
    applied_position: 'Group Partner',
    stage: 'offer',
    applied_date: '2025-12-28',
    source: 'Network',
    ai_match_score: 96,
    skills: ['Product Strategy', 'Founder Experience', 'Growth', 'Mentorship'],
    experience_years: 14,
  },
  {
    id: 'cand_003',
    first_name: 'Emily',
    last_name: 'Zhang',
    email: 'emily.zhang@berkeley.edu',
    current_company: 'OpenAI',
    current_title: 'Research Lead',
    applied_position: 'Group Partner - AI/ML',
    stage: 'interview',
    applied_date: '2026-01-02',
    source: 'LinkedIn',
    ai_match_score: 91,
    skills: ['AI/ML', 'Research', 'Technical Leadership', 'Startup Advisory'],
    experience_years: 10,
  },
  {
    id: 'cand_004',
    first_name: 'Jason',
    last_name: 'Park',
    email: 'jason.park@outlook.com',
    current_company: 'Figma',
    current_title: 'VP Engineering',
    applied_position: 'Group Partner',
    stage: 'screening',
    applied_date: '2026-01-08',
    source: 'Referral',
    ai_match_score: 88,
    skills: ['Engineering Leadership', 'Scaling Teams', 'Product Development'],
    experience_years: 15,
  },
  {
    id: 'cand_005',
    first_name: 'Amanda',
    last_name: 'Rodriguez',
    email: 'amanda.r@gmail.com',
    current_company: 'Google',
    current_title: 'Senior Program Manager',
    applied_position: 'Batch Operations Lead',
    stage: 'interview',
    applied_date: '2026-01-03',
    source: 'Job Board',
    ai_match_score: 85,
    skills: ['Program Management', 'Operations', 'Event Planning', 'Stakeholder Management'],
    experience_years: 8,
  },
  {
    id: 'cand_006',
    first_name: 'David',
    last_name: 'Kim',
    email: 'david.kim@mit.edu',
    current_company: 'a]6z',
    current_title: 'Principal',
    applied_position: 'Visiting Partner',
    stage: 'applied',
    applied_date: '2026-01-09',
    source: 'Network',
    ai_match_score: 89,
    skills: ['Venture Capital', 'Due Diligence', 'Portfolio Management', 'Fintech'],
    experience_years: 11,
  },
  {
    id: 'cand_007',
    first_name: 'Jessica',
    last_name: 'Liu',
    email: 'jessica.liu@yahoo.com',
    current_company: 'Notion',
    current_title: 'Staff Software Engineer',
    applied_position: 'Senior Software Engineer',
    stage: 'interview',
    applied_date: '2026-01-04',
    source: 'LinkedIn',
    ai_match_score: 92,
    skills: ['Full Stack', 'React', 'Python', 'System Design'],
    experience_years: 7,
  },
  {
    id: 'cand_008',
    first_name: 'Michael',
    last_name: 'Thompson',
    email: 'michael.t@proton.me',
    current_company: 'Sequoia',
    current_title: 'Associate',
    applied_position: 'Group Partner',
    stage: 'screening',
    applied_date: '2026-01-07',
    source: 'Referral',
    ai_match_score: 83,
    skills: ['Investment Analysis', 'Deal Sourcing', 'Portfolio Support'],
    experience_years: 6,
  },
  {
    id: 'cand_009',
    first_name: 'Rachel',
    last_name: 'Foster',
    email: 'rachel.f@gmail.com',
    current_company: 'Meta',
    current_title: 'Events Director',
    applied_position: 'Demo Day Lead',
    stage: 'applied',
    applied_date: '2026-01-10',
    source: 'Job Board',
    ai_match_score: 87,
    skills: ['Event Management', 'Executive Relations', 'Vendor Management', 'Budgeting'],
    experience_years: 9,
  },
  {
    id: 'cand_010',
    first_name: 'Kevin',
    last_name: 'Nguyen',
    email: 'kevin.n@outlook.com',
    current_company: 'Brex',
    current_title: 'Finance Manager',
    applied_position: 'Controller',
    stage: 'interview',
    applied_date: '2026-01-06',
    source: 'LinkedIn',
    ai_match_score: 84,
    skills: ['Financial Reporting', 'Audit', 'GAAP', 'FP&A'],
    experience_years: 8,
  },
  {
    id: 'cand_011',
    first_name: 'Brandon',
    last_name: 'Lee',
    email: 'brandon.lee@stanford.edu',
    current_company: 'Vercel',
    current_title: 'Software Engineer',
    applied_position: 'Software Engineer',
    stage: 'hired',
    applied_date: '2025-12-15',
    source: 'Referral',
    ai_match_score: 93,
    skills: ['TypeScript', 'Next.js', 'React', 'Node.js'],
    experience_years: 5,
  },
  {
    id: 'cand_012',
    first_name: 'Sophia',
    last_name: 'Martinez',
    email: 'sophia.m@gmail.com',
    current_company: 'DoorDash',
    current_title: 'Operations Manager',
    applied_position: 'Batch Operations Manager',
    stage: 'rejected',
    applied_date: '2025-12-20',
    source: 'Job Board',
    ai_match_score: 62,
    skills: ['Operations', 'Logistics', 'Process Improvement'],
    experience_years: 4,
  },
  {
    id: 'cand_013',
    first_name: 'Alexander',
    last_name: 'Johnson',
    email: 'alex.j@proton.me',
    current_company: 'Scale AI',
    current_title: 'Product Lead',
    applied_position: 'Group Partner - AI/ML',
    stage: 'screening',
    applied_date: '2026-01-08',
    source: 'Network',
    ai_match_score: 86,
    skills: ['AI Product', 'ML Infrastructure', 'Team Building', 'Strategy'],
    experience_years: 9,
  },
  {
    id: 'cand_014',
    first_name: 'Nicole',
    last_name: 'Wang',
    email: 'nicole.w@berkeley.edu',
    current_company: 'Retool',
    current_title: 'Design Lead',
    applied_position: 'Product Designer',
    stage: 'interview',
    applied_date: '2026-01-01',
    source: 'LinkedIn',
    ai_match_score: 90,
    skills: ['Product Design', 'Figma', 'User Research', 'Design Systems'],
    experience_years: 6,
  },
  {
    id: 'cand_015',
    first_name: 'Christopher',
    last_name: 'Davis',
    email: 'chris.d@gmail.com',
    current_company: 'Coinbase',
    current_title: 'Senior Counsel',
    applied_position: 'Corporate Counsel',
    stage: 'applied',
    applied_date: '2026-01-09',
    source: 'Referral',
    ai_match_score: 82,
    skills: ['Corporate Law', 'Securities', 'M&A', 'Venture Transactions'],
    experience_years: 8,
  },
  {
    id: 'cand_016',
    first_name: 'Olivia',
    last_name: 'Brown',
    email: 'olivia.b@yahoo.com',
    current_company: 'Snap',
    current_title: 'EA to CEO',
    applied_position: 'Executive Assistant',
    stage: 'screening',
    applied_date: '2026-01-07',
    source: 'Job Board',
    ai_match_score: 88,
    skills: ['Executive Support', 'Calendar Management', 'Travel', 'Confidentiality'],
    experience_years: 7,
  },
  {
    id: 'cand_017',
    first_name: 'Daniel',
    last_name: 'Garcia',
    email: 'daniel.g@outlook.com',
    current_company: 'Plaid',
    current_title: 'Data Engineer',
    applied_position: 'Data Engineer',
    stage: 'interview',
    applied_date: '2026-01-02',
    source: 'LinkedIn',
    ai_match_score: 89,
    skills: ['Python', 'SQL', 'Spark', 'Data Pipelines', 'dbt'],
    experience_years: 5,
  },
  {
    id: 'cand_018',
    first_name: 'Samantha',
    last_name: 'Wilson',
    email: 'sam.wilson@proton.me',
    current_company: 'Benchmark',
    current_title: 'Platform Lead',
    applied_position: 'Visiting Partner',
    stage: 'offer',
    applied_date: '2025-12-22',
    source: 'Network',
    ai_match_score: 95,
    skills: ['Venture Capital', 'Portfolio Services', 'Founder Support', 'Network'],
    experience_years: 10,
  },
  {
    id: 'cand_019',
    first_name: 'James',
    last_name: 'Anderson',
    email: 'james.a@gmail.com',
    current_company: 'Flexport',
    current_title: 'DevOps Lead',
    applied_position: 'DevOps Engineer',
    stage: 'applied',
    applied_date: '2026-01-10',
    source: 'Job Board',
    ai_match_score: 81,
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD'],
    experience_years: 6,
  },
  {
    id: 'cand_020',
    first_name: 'Lauren',
    last_name: 'Taylor',
    email: 'lauren.t@stanford.edu',
    current_company: 'Kleiner Perkins',
    current_title: 'Associate',
    applied_position: 'Group Partner',
    stage: 'screening',
    applied_date: '2026-01-06',
    source: 'Referral',
    ai_match_score: 79,
    skills: ['Investment', 'Due Diligence', 'Healthcare', 'Biotech'],
    experience_years: 5,
  },
];

// ============================================================================
// PTO REQUESTS (10 pending)
// ============================================================================

export const demoPTORequests: DemoPTORequest[] = [
  {
    id: 'pto_001',
    employee_id: 'emp_006',
    type: 'vacation',
    start_date: '2026-01-20',
    end_date: '2026-01-24',
    days: 5,
    status: 'pending',
    reason: 'Family vacation to Hawaii',
  },
  {
    id: 'pto_002',
    employee_id: 'emp_010',
    type: 'personal',
    start_date: '2026-01-15',
    end_date: '2026-01-15',
    days: 1,
    status: 'pending',
    reason: 'Personal appointment',
  },
  {
    id: 'pto_003',
    employee_id: 'emp_027',
    type: 'vacation',
    start_date: '2026-02-01',
    end_date: '2026-02-07',
    days: 5,
    status: 'pending',
    reason: 'Post-batch break',
  },
  {
    id: 'pto_004',
    employee_id: 'emp_039',
    type: 'sick',
    start_date: '2026-01-13',
    end_date: '2026-01-14',
    days: 2,
    status: 'pending',
    reason: 'Feeling unwell',
  },
  {
    id: 'pto_005',
    employee_id: 'emp_042',
    type: 'vacation',
    start_date: '2026-01-27',
    end_date: '2026-01-31',
    days: 5,
    status: 'pending',
    reason: 'Conference + vacation',
  },
  {
    id: 'pto_006',
    employee_id: 'emp_047',
    type: 'personal',
    start_date: '2026-01-16',
    end_date: '2026-01-17',
    days: 2,
    status: 'pending',
    reason: 'Moving',
  },
  {
    id: 'pto_007',
    employee_id: 'emp_033',
    type: 'vacation',
    start_date: '2026-02-10',
    end_date: '2026-02-14',
    days: 5,
    status: 'pending',
    reason: 'Anniversary trip',
  },
  {
    id: 'pto_008',
    employee_id: 'emp_045',
    type: 'sick',
    start_date: '2026-01-12',
    end_date: '2026-01-12',
    days: 1,
    status: 'pending',
    reason: 'Doctor appointment',
  },
  {
    id: 'pto_009',
    employee_id: 'emp_011',
    type: 'vacation',
    start_date: '2026-01-22',
    end_date: '2026-01-24',
    days: 3,
    status: 'approved',
  },
  {
    id: 'pto_010',
    employee_id: 'emp_015',
    type: 'vacation',
    start_date: '2026-02-03',
    end_date: '2026-02-07',
    days: 5,
    status: 'approved',
    reason: 'Founder conference',
  },
];

// ============================================================================
// TEAMS
// ============================================================================

export const demoTeams: DemoTeam[] = [
  {
    id: 'team_001',
    name: 'Growth',
    department: 'Partners',
    manager_id: 'emp_006',
    member_count: 3,
    health_score: 86,
    avg_engagement: 87,
  },
  {
    id: 'team_002',
    name: 'Enterprise',
    department: 'Partners',
    manager_id: 'emp_007',
    member_count: 4,
    health_score: 90,
    avg_engagement: 89,
  },
  {
    id: 'team_003',
    name: 'AI/ML',
    department: 'Partners',
    manager_id: 'emp_010',
    member_count: 3,
    health_score: 93,
    avg_engagement: 93,
  },
  {
    id: 'team_004',
    name: 'Batch Ops',
    department: 'Operations',
    manager_id: 'emp_027',
    member_count: 4,
    health_score: 89,
    avg_engagement: 90,
  },
  {
    id: 'team_005',
    name: 'Events',
    department: 'Operations',
    manager_id: 'emp_030',
    member_count: 3,
    health_score: 68,
    avg_engagement: 74,
  },
  {
    id: 'team_006',
    name: 'Platform',
    department: 'Engineering',
    manager_id: 'emp_038',
    member_count: 4,
    health_score: 88,
    avg_engagement: 87,
  },
  {
    id: 'team_007',
    name: 'Visiting',
    department: 'Partners',
    manager_id: 'emp_001',
    member_count: 5,
    health_score: 81,
    avg_engagement: 82,
  },
  {
    id: 'team_008',
    name: 'Consumer',
    department: 'Partners',
    manager_id: 'emp_008',
    member_count: 2,
    health_score: 82,
    avg_engagement: 86,
  },
];

// ============================================================================
// ORG STATS - Y Combinator
// ============================================================================

export const demoOrgStats = {
  totalEmployees: 50,
  avgEngagement: 87,
  avgPerformance: 4.38,
  highFlightRisk: 3,
  mediumFlightRisk: 7,
  openPositions: 6,
  activeCandidates: 15,
  pendingPTO: 8,
  departments: 6,
  avgTenure: 3.2, // years
  turnoverRisk: 8, // %
  batchesRun: 48,
  companiesFunded: 5000,
  totalPortfolioValue: '$600B+',
  headcount: {
    Partners: 20,
    Operations: 12,
    Engineering: 8,
    Finance: 3,
    Legal: 2,
    Leadership: 5,
  },
  sentimentTrend: [0.82, 0.83, 0.84, 0.85, 0.86, 0.87],
  engagementTrend: [84, 85, 85, 86, 87, 87],
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getEmployeeById(id: string): DemoEmployee | undefined {
  return demoEmployees.find((e) => e.id === id);
}

export function getEmployeesByDepartment(department: string): DemoEmployee[] {
  return demoEmployees.filter((e) => e.department === department);
}

export function getFlightRiskEmployees(): DemoEmployee[] {
  return demoEmployees.filter((e) => e.flight_risk === 'high' || e.flight_risk === 'medium');
}

export function getHighPerformers(): DemoEmployee[] {
  return demoEmployees.filter((e) => e.performance_rating >= 4.4);
}

export function getCandidatesByStage(stage: DemoCandidate['stage']): DemoCandidate[] {
  return demoCandidates.filter((c) => c.stage === stage);
}

export function getPendingPTORequests(): DemoPTORequest[] {
  return demoPTORequests.filter((p) => p.status === 'pending');
}

export function getDirectReports(managerId: string): DemoEmployee[] {
  return demoEmployees.filter((e) => e.manager_id === managerId);
}
